version: '3'
services:        
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3001:3000"
        volumes:
            - ./confs/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/data:/var/lib/grafana #chown 472:472 grafana/data
        links:
            - "influxdb"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    influxdb:
        image: influxdb:latest
        ports:
            - "8086:8086"
            - "8083:8083"
        volumes:
            - ./influxdb/data:/var/lib/influxdb
    mqtt:
        build: ./MQTT
        image: mqtt
        ports:
            - "1883:3030"
