services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3001:3000"
        volumes:
            - "./confs/grafana.ini:/etc/grafana/grafana.ini"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    influxdb:
        image: influxdb:latest
        ports:
            - "8086:8086"
            - "8083:8083"
    mqtt:
        image: mqtt:latest
        links:
            - "redis"
            - "influxdb"
        network_mode: 'host'
